<?xml version="1.0"?>
<package format="3">
  <name>pallet_rack_detector_cpp</name>
  <version>0.0.1</version>
  <description>Detect a 4-leg pallet rack from 2D LaserScan and publish pose/markers.</description>
  <maintainer email="vutienphat1404@gmail.com">Vu Tien Phat</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>std_msgs</depend>

  <exec_depend>rviz2</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
